version: '3'  
services:  
    database:
      build: ./database
      ports:
        - "3306:3306"

    users-service:
      build: ./backend
      ports:
        - "8080:8080"
      environment:
        - DATABASE_HOST=database
      depends_on:
         - database
     
    user-ui:
      build: ./picpay-ui
      depends_on: 
        - users-service
      ports:
        - 3000:80
